In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/Colab/setik/dataset/vehicles.csv")
df.shape

(426880, 26)

In [14]:
for i in df.columns:
  print(i)

id
url
region
region_url
price
year
manufacturer
model
condition
cylinders
fuel
odometer
title_status
transmission
VIN
drive
size
type
paint_color
image_url
description
county
state
lat
long
posting_date

In [15]:
df_filtered = df.filter([
    'region',
    'price',
    'year',
    'manufacturer',
    'model',
    'condition',
    'cylinders',
    'fuel',
    'odometer',
    'title_status',
    'transmission',
    'drive',
    'size',
    'type',
    'paint_color',
    'state',
    'posting_date'
]);
df.shape

(426880, 26)

In [16]:
df_filtered.to_csv("/content/drive/My Drive/Colab/setik/dataset/100-remove-features.csv", index=False)